#!/bin/bash
clear
#echo $0
#echo $1
avr-gcc -Os -DF_CPU=1000000UL -mmcu=atmega328  -o $1.elf $1.c
avr-objcopy -O ihex -R .eeprom $1.elf $1.ihx
sudo avrdude -vv -c arduino -p atmega328p -P /dev/ttyUSB0 -b 57600 -U flash:w:$1.ihx
